name: release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write
  statuses: write

jobs:
  release:
    name: release
    if: ${{ github.repository_owner == 'bigbang-sdk' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
