name: release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write
  statuses: write

jobs:
  release:
    name: release
    if: ${{ github.repository_owner == 'bigbang-sdk' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Get latest Git tag
        id: latest_git
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true
          with_initial_version: true
          initial_version: 'v0.0.0'
          
      - name: Print latest Git tag
        run: echo "Latest Git tag is ${{ steps.latest_git.outputs.tag }}"
